version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  backend:
    build:
      context: ./food
      dockerfile: Dockerfile
    image: food-app-backend:latest
    container_name: mannahub-backend
    ports:
      - "9092:9092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://food-rds.cunmy820cn5a.us-east-1.rds.amazonaws.com:3306/food?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 8897823543
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
    depends_on:
      - minio
    restart: always

  frontend:
    build:
      context: . # 👈 Changed from ./food-frontend
      dockerfile: ./food-frontend/Dockerfile # 👈 Updated path
    image: food-app-frontend:latest
    container_name: mannahub-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  minio_data:
